apiVersion: apps/v1
kind: Deployment
metadata:
  name: techday-gitops-demo
  namespace: gitops-demo  
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: techday-gitops-demo
  template:
    metadata:
      labels:
        app: techday-gitops-demo
    spec:
      containers:
      - image: docker.io/mukiwa/gitops-demo:latest
        imagePullPolicy: Always
        name: techday-gitops-demo
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi