apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mitra-techday-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Astonie/techday-gitops-demo
    targetRevision: HEAD
    path: development

  destination: 
    server: https://kubernetes.default.svc
    namespace: gitops-demo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true